/**
 * Created by viktor on 5/24/2016.
 */
/*global __g_sm, ko, _, _campaignID, Tracx, */

define(
    ['knockout'],
    function()
    {

        'use strict';

        /**
         * constructor
         * @constructor
         */
        function Tables()
        {
            this.tableInstance = ko.observable();
            this.tableSampleData =
                [
                    {
                        "postId": 1,
                        "id": 1,
                        "name": "id labore ex et quam laborum",
                        "email": "Eliseo@gardner.biz",
                        "body": "laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor quam autem quasi\nreiciendis et nam sapiente accusantium"
                    },
                    {
                        "postId": 1,
                        "id": 2,
                        "name": "quo vero reiciendis velit similique earum",
                        "email": "Jayne_Kuhic@sydney.com",
                        "body": "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et"
                    },
                    {
                        "postId": 1,
                        "id": 3,
                        "name": "odio adipisci rerum aut animi",
                        "email": "Nikita@garfield.biz",
                        "body": "quia molestiae reprehenderit quasi aspernatur\naut expedita occaecati aliquam eveniet laudantium\nomnis quibusdam delectus saepe quia accusamus maiores nam est\ncum et ducimus et vero voluptates excepturi deleniti ratione"
                    },
                    {
                        "postId": 1,
                        "id": 4,
                        "name": "alias odio sit",
                        "email": "Lew@alysha.tv",
                        "body": "non et atque\noccaecati deserunt quas accusantium unde odit nobis qui voluptatem\nquia voluptas consequuntur itaque dolor\net qui rerum deleniti ut occaecati"
                    },
                    {
                        "postId": 1,
                        "id": 5,
                        "name": "vero eaque aliquid doloribus et culpa",
                        "email": "Hayden@althea.biz",
                        "body": "harum non quasi et ratione\ntempore iure ex voluptates in ratione\nharum architecto fugit inventore cupiditate\nvoluptates magni quo et"
                    },
                    {
                        "postId": 2,
                        "id": 6,
                        "name": "et fugit eligendi deleniti quidem qui sint nihil autem",
                        "email": "Presley.Mueller@myrl.com",
                        "body": "doloribus at sed quis culpa deserunt consectetur qui praesentium\naccusamus fugiat dicta\nvoluptatem rerum ut voluptate autem\nvoluptatem repellendus aspernatur dolorem in"
                    },
                    {
                        "postId": 2,
                        "id": 7,
                        "name": "repellat consequatur praesentium vel minus molestias voluptatum",
                        "email": "Dallas@ole.me",
                        "body": "maiores sed dolores similique labore et inventore et\nquasi temporibus esse sunt id et\neos voluptatem aliquam\naliquid ratione corporis molestiae mollitia quia et magnam dolor"
                    },
                    {
                        "postId": 2,
                        "id": 8,
                        "name": "et omnis dolorem",
                        "email": "Mallory_Kunze@marie.org",
                        "body": "ut voluptatem corrupti velit\nad voluptatem maiores\net nisi velit vero accusamus maiores\nvoluptates quia aliquid ullam eaque"
                    },
                    {
                        "postId": 2,
                        "id": 9,
                        "name": "provident id voluptas",
                        "email": "Meghan_Littel@rene.us",
                        "body": "sapiente assumenda molestiae atque\nadipisci laborum distinctio aperiam et ab ut omnis\net occaecati aspernatur odit sit rem expedita\nquas enim ipsam minus"
                    },
                    {
                        "postId": 2,
                        "id": 10,
                        "name": "eaque et deleniti atque tenetur ut quo ut",
                        "email": "Carmen_Keeling@caroline.name",
                        "body": "voluptate iusto quis nobis reprehenderit ipsum amet nulla\nquia quas dolores velit et non\naut quia necessitatibus\nnostrum quaerat nulla et accusamus nisi facilis"
                    },
                    {
                        "postId": 2,
                        "id": 11,
                        "name": "eaque et deleniti atque tenetur ut quo ut",
                        "email": "Carmen_Keeling@caroline.name",
                        "body": "voluptate iusto quis nobis reprehenderit ipsum amet nulla\nquia quas dolores velit et non\naut quia necessitatibus\nnostrum quaerat nulla et accusamus nisi facilis"
                    },
                    {
                        "postId": 2,
                        "id": 12,
                        "name": "eaque",
                        "email": "Carmen@caroline.name",
                        "body": "voluptate iusto quis nobis reprehenderit ipsum amet nulla\nquia quas dolores velit et non\naut quia necessitatibus\nnostrum quaerat nulla et accusamus nisi facilis"
                    }];

            this.tableInstanceB = ko.observable();
            this.tableSampleDataB =
                [
                    {
                        "ad_id": "6021732873710",
                        "ad_account_id": "1395469910722175",
                        "ad_account_currency": "ILS",
                        "ad_campaign_id": "6021732870710",
                        "ad_campaign_name": "Duckies - Post Engagement",
                        "ad_campaign_objective": "POST_ENGAGEMENT",
                        "ad_set_id": "6021732871510",
                        "ad_set_name": "Tel Aviv - W - 18-24",
                        "ad_set_optimization_goal": "POST_ENGAGEMENT",
                        "type": "1",
                        "delivery": "0",
                        "created_date": "2015-03-22 13:02:31",
                        "publish_date": "2014-07-30 09:09:49",
                        "start_date": "2015-03-22 13:02:29",
                        "end_date": "2015-04-01 10:57:00",
                        "object_id": "97602041",
                        "object_date_posted": "2014-07-30 09:09:49",
                        "object_content_type": null,
                        "page_id": "1451243768479079",
                        "page_owner_id": "61208574",
                        "creating_user_id": null,
                        "tx_total_interactions_count": "0",
                        "tx_comments_count": "0",
                        "tx_likes_count": "0",
                        "tx_shares_count": "0",
                        "tx_post_impressions_unique": "1",
                        "ad_comments_count": "0",
                        "ad_likes_count": "0",
                        "ad_shares_count": "0",
                        "ad_clicks_count": "1",
                        "ad_reach": "286",
                        "ad_unique_actions": "1",
                        "ad_impressions": "386",
                        "ad_post_engagement": "1",
                        "ad_ctr": "0.25906735751295",
                        "ad_cpm": "12.953367875648",
                        "ad_cpc": "5",
                        "avg_cost_per_engagement": "5",
                        "total_budget": "500",
                        "daily_budget": "0",
                        "budget_spent": "500",
                        "ad_effective_status": "ADSET_PAUSED",
                        "ad_configured_status": "ACTIVE",
                        "post_is_published": "1",
                        "date_record_updated": "2017-01-19 10:31:30"
                    },
                    {
                        "ad_id": "6023108488710",
                        "ad_account_id": "1395469910722175",
                        "ad_account_currency": "ILS",
                        "ad_campaign_id": "6021732870710",
                        "ad_campaign_name": "Duckies - Post Engagement",
                        "ad_campaign_objective": "POST_ENGAGEMENT",
                        "ad_set_id": "6023107834910",
                        "ad_set_name": "Tel Aviv - W - 18-24",
                        "ad_set_optimization_goal": "POST_ENGAGEMENT",
                        "type": "3",
                        "delivery": "0",
                        "created_date": "2015-04-21 07:55:56",
                        "publish_date": "2015-04-21 04:23:01",
                        "start_date": "2015-04-21 07:09:46",
                        "end_date": null,
                        "object_id": "97602039",
                        "object_date_posted": "2015-04-21 04:23:01",
                        "object_content_type": null,
                        "page_id": "1451243768479079",
                        "page_owner_id": "61208574",
                        "creating_user_id": null,
                        "tx_total_interactions_count": "0",
                        "tx_comments_count": "0",
                        "tx_likes_count": "0",
                        "tx_shares_count": "0",
                        "tx_post_impressions_unique": "3",
                        "ad_comments_count": "0",
                        "ad_likes_count": "0",
                        "ad_shares_count": "0",
                        "ad_clicks_count": "0",
                        "ad_reach": "0",
                        "ad_unique_actions": "0",
                        "ad_impressions": "0",
                        "ad_post_engagement": "0",
                        "ad_ctr": "0",
                        "ad_cpm": "0",
                        "ad_cpc": "0",
                        "avg_cost_per_engagement": "0",
                        "total_budget": "0",
                        "daily_budget": "500",
                        "budget_spent": "0",
                        "ad_effective_status": "PAUSED",
                        "ad_configured_status": "PAUSED",
                        "post_is_published": "1",
                        "date_record_updated": "2017-01-19 10:31:30"
                    },
                    {
                        "ad_id": "6023108495910",
                        "ad_account_id": "1395469910722175",
                        "ad_account_currency": "ILS",
                        "ad_campaign_id": "6021732870710",
                        "ad_campaign_name": "Duckies - Post Engagement",
                        "ad_campaign_objective": "POST_ENGAGEMENT",
                        "ad_set_id": "6023107834910",
                        "ad_set_name": "Tel Aviv - W - 18-24",
                        "ad_set_optimization_goal": "POST_ENGAGEMENT",
                        "type": "1",
                        "delivery": "0",
                        "created_date": "2015-04-21 07:56:14",
                        "publish_date": "2015-04-21 06:14:23",
                        "start_date": "2015-04-21 07:09:46",
                        "end_date": null,
                        "object_id": "97602028",
                        "object_date_posted": "2015-04-21 06:14:23",
                        "object_content_type": null,
                        "page_id": "328438747241560",
                        "page_owner_id": "61208573",
                        "creating_user_id": null,
                        "tx_total_interactions_count": "0",
                        "tx_comments_count": "0",
                        "tx_likes_count": "0",
                        "tx_shares_count": "0",
                        "tx_post_impressions_unique": "8",
                        "ad_comments_count": "0",
                        "ad_likes_count": "0",
                        "ad_shares_count": "0",
                        "ad_clicks_count": "0",
                        "ad_reach": "0",
                        "ad_unique_actions": "0",
                        "ad_impressions": "0",
                        "ad_post_engagement": "0",
                        "ad_ctr": "0",
                        "ad_cpm": "0",
                        "ad_cpc": "0",
                        "avg_cost_per_engagement": "0",
                        "total_budget": "0",
                        "daily_budget": "500",
                        "budget_spent": "0",
                        "ad_effective_status": "PAUSED",
                        "ad_configured_status": "PAUSED",
                        "post_is_published": "1",
                        "date_record_updated": "2017-02-22 15:19:34"
                    },
                    {
                        "ad_id": "6026098479510",
                        "ad_account_id": "1395469910722175",
                        "ad_account_currency": "ILS",
                        "ad_campaign_id": "6026098477310",
                        "ad_campaign_name": "Post: \"Targeting a post\"",
                        "ad_campaign_objective": "POST_ENGAGEMENT",
                        "ad_set_id": "6026098478110",
                        "ad_set_name": "Post: \"Targeting a post\"",
                        "ad_set_optimization_goal": "POST_ENGAGEMENT",
                        "type": "3",
                        "delivery": "0",
                        "created_date": "2015-07-06 12:07:40",
                        "publish_date": "2015-07-06 12:06:44",
                        "start_date": "2015-07-06 12:07:40",
                        "end_date": "2015-07-07 12:07:40",
                        "object_id": "97602036",
                        "object_date_posted": "2015-07-06 12:06:44",
                        "object_content_type": null,
                        "page_id": "1451243768479079",
                        "page_owner_id": "61208574",
                        "creating_user_id": null,
                        "tx_total_interactions_count": "0",
                        "tx_comments_count": "0",
                        "tx_likes_count": "0",
                        "tx_shares_count": "0",
                        "tx_post_impressions_unique": "0",
                        "ad_comments_count": "0",
                        "ad_likes_count": "0",
                        "ad_shares_count": "0",
                        "ad_clicks_count": "0",
                        "ad_reach": "0",
                        "ad_unique_actions": "0",
                        "ad_impressions": "0",
                        "ad_post_engagement": "0",
                        "ad_ctr": "0",
                        "ad_cpm": "0",
                        "ad_cpc": "0",
                        "avg_cost_per_engagement": "0",
                        "total_budget": "500",
                        "daily_budget": "0",
                        "budget_spent": "0",
                        "ad_effective_status": "ADSET_PAUSED",
                        "ad_configured_status": "ACTIVE",
                        "post_is_published": "1",
                        "date_record_updated": "2017-01-19 10:31:30"
                    },
                    {
                        "ad_id": "6026656543910",
                        "ad_account_id": "1395469910722175",
                        "ad_account_currency": "ILS",
                        "ad_campaign_id": "6026656541110",
                        "ad_campaign_name": "Test",
                        "ad_campaign_objective": "POST_ENGAGEMENT",
                        "ad_set_id": "6026656541910",
                        "ad_set_name": "Boost most recent post from page",
                        "ad_set_optimization_goal": "POST_ENGAGEMENT",
                        "type": "3",
                        "delivery": "0",
                        "created_date": "2015-07-23 12:32:45",
                        "publish_date": "2015-07-22 14:24:12",
                        "start_date": "2015-07-23 12:32:45",
                        "end_date": "2015-07-24 12:30:00",
                        "object_id": "97602035",
                        "object_date_posted": "2015-07-22 14:24:12",
                        "object_content_type": null,
                        "page_id": "328438747241560",
                        "page_owner_id": "61208573",
                        "creating_user_id": null,
                        "tx_total_interactions_count": "6",
                        "tx_comments_count": "3",
                        "tx_likes_count": "1",
                        "tx_shares_count": "2",
                        "tx_post_impressions_unique": "159",
                        "ad_comments_count": "0",
                        "ad_likes_count": "0",
                        "ad_shares_count": "0",
                        "ad_clicks_count": "0",
                        "ad_reach": "134",
                        "ad_unique_actions": "0",
                        "ad_impressions": "134",
                        "ad_post_engagement": "0",
                        "ad_ctr": "0",
                        "ad_cpm": "37.313432835821",
                        "ad_cpc": "0",
                        "avg_cost_per_engagement": "0",
                        "total_budget": "500",
                        "daily_budget": "0",
                        "budget_spent": "500",
                        "ad_effective_status": "ADSET_PAUSED",
                        "ad_configured_status": "ACTIVE",
                        "post_is_published": "1",
                        "date_record_updated": "2017-01-19 10:31:30"
                    },
                    {
                        "ad_id": "6028831824510",
                        "ad_account_id": "1395469910722175",
                        "ad_account_currency": "ILS",
                        "ad_campaign_id": "6028831820710",
                        "ad_campaign_name": "Post: \"Rubber Duckies Lover \"",
                        "ad_campaign_objective": "POST_ENGAGEMENT",
                        "ad_set_id": "6028831821910",
                        "ad_set_name": "Post: \"Rubber Duckies Lover \"",
                        "ad_set_optimization_goal": "POST_ENGAGEMENT",
                        "type": "2",
                        "delivery": "0",
                        "created_date": "2015-09-16 09:49:03",
                        "publish_date": "2015-09-16 09:47:05",
                        "start_date": "2015-09-16 09:49:03",
                        "end_date": "2015-11-10 00:00:00",
                        "object_id": "97602032",
                        "object_date_posted": "2015-09-16 09:47:05",
                        "object_content_type": null,
                        "page_id": "1451243768479079",
                        "page_owner_id": "61208574",
                        "creating_user_id": null,
                        "tx_total_interactions_count": "9",
                        "tx_comments_count": "1",
                        "tx_likes_count": "7",
                        "tx_shares_count": "1",
                        "tx_post_impressions_unique": "0",
                        "ad_comments_count": "0",
                        "ad_likes_count": "4",
                        "ad_shares_count": "1",
                        "ad_clicks_count": "7",
                        "ad_reach": "253",
                        "ad_unique_actions": "5",
                        "ad_impressions": "253",
                        "ad_post_engagement": "5",
                        "ad_ctr": "2.7667984189723",
                        "ad_cpm": "19.762845849802",
                        "ad_cpc": "0.71428571428571",
                        "avg_cost_per_engagement": "1",
                        "total_budget": "140000",
                        "daily_budget": "0",
                        "budget_spent": "500",
                        "ad_effective_status": "PAUSED",
                        "ad_configured_status": "PAUSED",
                        "post_is_published": "1",
                        "date_record_updated": "2017-01-19 10:31:30"
                    },
                    {
                        "ad_id": "6029626097110",
                        "ad_account_id": "1395469910722175",
                        "ad_account_currency": "ILS",
                        "ad_campaign_id": "6029626094710",
                        "ad_campaign_name": "Post: \"Title - caption\"",
                        "ad_campaign_objective": "POST_ENGAGEMENT",
                        "ad_set_id": "6029626095710",
                        "ad_set_name": "Post: \"Title - caption\"",
                        "ad_set_optimization_goal": "POST_ENGAGEMENT",
                        "type": "3",
                        "delivery": "0",
                        "created_date": "2015-09-29 09:01:00",
                        "publish_date": "2015-09-29 08:32:24",
                        "start_date": "2015-09-29 09:01:00",
                        "end_date": "2015-09-30 09:01:00",
                        "object_id": "97602034",
                        "object_date_posted": "2015-09-29 08:32:24",
                        "object_content_type": null,
                        "page_id": "1451243768479079",
                        "page_owner_id": "61208574",
                        "creating_user_id": null,
                        "tx_total_interactions_count": "0",
                        "tx_comments_count": "0",
                        "tx_likes_count": "0",
                        "tx_shares_count": "0",
                        "tx_post_impressions_unique": "0",
                        "ad_comments_count": "0",
                        "ad_likes_count": "0",
                        "ad_shares_count": "0",
                        "ad_clicks_count": "0",
                        "ad_reach": "0",
                        "ad_unique_actions": "0",
                        "ad_impressions": "0",
                        "ad_post_engagement": "0",
                        "ad_ctr": "0",
                        "ad_cpm": "0",
                        "ad_cpc": "0",
                        "avg_cost_per_engagement": "0",
                        "total_budget": "500",
                        "daily_budget": "0",
                        "budget_spent": "0",
                        "ad_effective_status": "PAUSED",
                        "ad_configured_status": "PAUSED",
                        "post_is_published": "1",
                        "date_record_updated": "2017-01-19 10:31:30"
                    },
                    {
                        "ad_id": "6029626218910",
                        "ad_account_id": "1395469910722175",
                        "ad_account_currency": "ILS",
                        "ad_campaign_id": "6029626216310",
                        "ad_campaign_name": "Duckies - Post Engagement",
                        "ad_campaign_objective": "POST_ENGAGEMENT",
                        "ad_set_id": "6029626217310",
                        "ad_set_name": "IL - 18+",
                        "ad_set_optimization_goal": "POST_ENGAGEMENT",
                        "type": "3",
                        "delivery": "0",
                        "created_date": "2015-09-29 09:04:18",
                        "publish_date": "2015-09-30 09:13:00",
                        "start_date": "2015-09-29 09:04:18",
                        "end_date": "2015-09-30 10:02:00",
                        "object_id": "97602033",
                        "object_date_posted": "2015-09-30 09:13:00",
                        "object_content_type": null,
                        "page_id": "1451243768479079",
                        "page_owner_id": "61208574",
                        "creating_user_id": null,
                        "tx_total_interactions_count": "0",
                        "tx_comments_count": "0",
                        "tx_likes_count": "0",
                        "tx_shares_count": "0",
                        "tx_post_impressions_unique": "0",
                        "ad_comments_count": "0",
                        "ad_likes_count": "0",
                        "ad_shares_count": "0",
                        "ad_clicks_count": "0",
                        "ad_reach": "0",
                        "ad_unique_actions": "0",
                        "ad_impressions": "0",
                        "ad_post_engagement": "0",
                        "ad_ctr": "0",
                        "ad_cpm": "0",
                        "ad_cpc": "0",
                        "avg_cost_per_engagement": "0",
                        "total_budget": "0",
                        "daily_budget": "500",
                        "budget_spent": "0",
                        "ad_effective_status": "PAUSED",
                        "ad_configured_status": "PAUSED",
                        "post_is_published": "1",
                        "date_record_updated": "2017-01-19 10:31:30"
                    },
                    {
                        "ad_id": "6032401446110",
                        "ad_account_id": "1395469910722175",
                        "ad_account_currency": "ILS",
                        "ad_campaign_id": "6032401440310",
                        "ad_campaign_name": "Tracx Campaign",
                        "ad_campaign_objective": "POST_ENGAGEMENT",
                        "ad_set_id": "6032401441910",
                        "ad_set_name": "Tracx Ad Set",
                        "ad_set_optimization_goal": "POST_ENGAGEMENT",
                        "type": "1",
                        "delivery": "0",
                        "created_date": "2015-11-16 11:58:08",
                        "publish_date": "2015-11-16 10:31:11",
                        "start_date": "2015-11-16 11:58:02",
                        "end_date": "2015-11-26 00:00:00",
                        "object_id": "97602030",
                        "object_date_posted": "2015-11-16 10:31:11",
                        "object_content_type": "1",
                        "page_id": "328438747241560",
                        "page_owner_id": "61208573",
                        "creating_user_id": null,
                        "tx_total_interactions_count": "0",
                        "tx_comments_count": "0",
                        "tx_likes_count": "0",
                        "tx_shares_count": "0",
                        "tx_post_impressions_unique": "11",
                        "ad_comments_count": "0",
                        "ad_likes_count": "0",
                        "ad_shares_count": "0",
                        "ad_clicks_count": "0",
                        "ad_reach": "0",
                        "ad_unique_actions": "0",
                        "ad_impressions": "0",
                        "ad_post_engagement": "0",
                        "ad_ctr": "0",
                        "ad_cpm": "0",
                        "ad_cpc": "0",
                        "avg_cost_per_engagement": "0",
                        "total_budget": "0",
                        "daily_budget": "100000",
                        "budget_spent": "0",
                        "ad_effective_status": "PAUSED",
                        "ad_configured_status": "PAUSED",
                        "post_is_published": "1",
                        "date_record_updated": "2017-02-23 14:47:18"
                    },
                    {
                        "ad_id": "6037185756310",
                        "ad_account_id": "1395469910722175",
                        "ad_account_currency": "ILS",
                        "ad_campaign_id": "6037185754110",
                        "ad_campaign_name": "Post: \"Duck Vader to the rescue!\"",
                        "ad_campaign_objective": "POST_ENGAGEMENT",
                        "ad_set_id": "6037185754910",
                        "ad_set_name": "Post: \"Duck Vader to the rescue!\"",
                        "ad_set_optimization_goal": "POST_ENGAGEMENT",
                        "type": "2",
                        "delivery": "0",
                        "created_date": "2016-02-08 15:12:43",
                        "publish_date": "2016-02-08 15:12:20",
                        "start_date": "2016-02-08 15:12:43",
                        "end_date": "2016-02-09 15:12:43",
                        "object_id": "97602029",
                        "object_date_posted": "2016-02-08 15:12:20",
                        "object_content_type": "2",
                        "page_id": "1451243768479079",
                        "page_owner_id": "61208574",
                        "creating_user_id": null,
                        "tx_total_interactions_count": "8",
                        "tx_comments_count": "1",
                        "tx_likes_count": "7",
                        "tx_shares_count": "0",
                        "tx_post_impressions_unique": "346",
                        "ad_comments_count": "1",
                        "ad_likes_count": "3",
                        "ad_shares_count": "0",
                        "ad_clicks_count": "8",
                        "ad_reach": "339",
                        "ad_unique_actions": "7",
                        "ad_impressions": "340",
                        "ad_post_engagement": "8",
                        "ad_ctr": "2.3529411764706",
                        "ad_cpm": "14.705882352941",
                        "ad_cpc": "0.625",
                        "avg_cost_per_engagement": "0.625",
                        "total_budget": "500",
                        "daily_budget": "0",
                        "budget_spent": "500",
                        "ad_effective_status": "ADSET_PAUSED",
                        "ad_configured_status": "ACTIVE",
                        "post_is_published": "1",
                        "date_record_updated": "2017-02-23 14:47:18"
                    },
                    {
                        "ad_id": "6047169091710",
                        "ad_account_id": "1395469910722175",
                        "ad_account_currency": "ILS",
                        "ad_campaign_id": "6047169088110",
                        "ad_campaign_name": "Tracx campaign 1047159695369458 07-13-2016",
                        "ad_campaign_objective": "POST_ENGAGEMENT",
                        "ad_set_id": "6047169089310",
                        "ad_set_name": "Tracx Ad Set",
                        "ad_set_optimization_goal": "POST_ENGAGEMENT",
                        "type": "3",
                        "delivery": "0",
                        "created_date": "2016-07-13 14:50:06",
                        "publish_date": "2016-07-13 14:49:00",
                        "start_date": "2016-07-13 14:50:04",
                        "end_date": "2016-07-15 00:00:00",
                        "object_id": "118396757",
                        "object_date_posted": "2016-07-13 14:49:00",
                        "object_content_type": null,
                        "page_id": "328438747241560",
                        "page_owner_id": "61208573",
                        "creating_user_id": null,
                        "tx_total_interactions_count": "0",
                        "tx_comments_count": "0",
                        "tx_likes_count": "0",
                        "tx_shares_count": "0",
                        "tx_post_impressions_unique": "0",
                        "ad_comments_count": "0",
                        "ad_likes_count": "0",
                        "ad_shares_count": "0",
                        "ad_clicks_count": "0",
                        "ad_reach": "0",
                        "ad_unique_actions": "0",
                        "ad_impressions": "0",
                        "ad_post_engagement": "0",
                        "ad_ctr": "0",
                        "ad_cpm": "0",
                        "ad_cpc": "0",
                        "avg_cost_per_engagement": "0",
                        "total_budget": "8547",
                        "daily_budget": "0",
                        "budget_spent": "0",
                        "ad_effective_status": "CAMPAIGN_PAUSED",
                        "ad_configured_status": "ACTIVE",
                        "post_is_published": "1",
                        "date_record_updated": "2017-01-19 10:31:30"
                    },
                    {
                        "ad_id": "6047411181110",
                        "ad_account_id": "1395469910722175",
                        "ad_account_currency": "ILS",
                        "ad_campaign_id": "6047411174710",
                        "ad_campaign_name": "Tracx campaign 1049782701773824 07-18-2016",
                        "ad_campaign_objective": "POST_ENGAGEMENT",
                        "ad_set_id": "6047411176310",
                        "ad_set_name": "Tracx Ad Set",
                        "ad_set_optimization_goal": "POST_ENGAGEMENT",
                        "type": "3",
                        "delivery": "0",
                        "created_date": "2016-07-17 14:43:02",
                        "publish_date": "2016-07-17 14:39:57",
                        "start_date": "2016-07-18 14:42:59",
                        "end_date": "2016-07-26 14:42:59",
                        "object_id": "118396915",
                        "object_date_posted": "2016-07-17 14:39:57",
                        "object_content_type": null,
                        "page_id": "328438747241560",
                        "page_owner_id": "61208573",
                        "creating_user_id": null,
                        "tx_total_interactions_count": "0",
                        "tx_comments_count": "0",
                        "tx_likes_count": "0",
                        "tx_shares_count": "0",
                        "tx_post_impressions_unique": "1",
                        "ad_comments_count": "0",
                        "ad_likes_count": "0",
                        "ad_shares_count": "0",
                        "ad_clicks_count": "0",
                        "ad_reach": "0",
                        "ad_unique_actions": "0",
                        "ad_impressions": "0",
                        "ad_post_engagement": "0",
                        "ad_ctr": "0",
                        "ad_cpm": "0",
                        "ad_cpc": "0",
                        "avg_cost_per_engagement": "0",
                        "total_budget": "67787",
                        "daily_budget": "0",
                        "budget_spent": "0",
                        "ad_effective_status": "CAMPAIGN_PAUSED",
                        "ad_configured_status": "ACTIVE",
                        "post_is_published": "1",
                        "date_record_updated": "2017-01-19 10:31:30"
                    }
                ];

            this.emailSorting = function(data, a, b)
            {
                var strA = a.email.toLowerCase(),
                    strB = b.email.toLowerCase();

                return ( strA === strB ) ? 0 : strA < strB ? -1 : 1;
            };
        }

        Tables.prototype.actionTest = function(_data)
        {
            Tracx.notifications.notify(Tracx.NotificationEnum.Type.INFO, 'actionTest', Tracx.notifications.SIZE.MEDIUM);
        };

        Tables.prototype.rowClick = function(_data)
        {
            Tracx.notifications.notify(Tracx.NotificationEnum.Type.INFO, 'row data From Table', Tracx.notifications.SIZE.MEDIUM);
        };

        Tables.prototype.switchTest = function(_data, event)
        {
            Tracx.notifications.notify(Tracx.NotificationEnum.Type.INFO, 'switchTest', Tracx.notifications.SIZE.MEDIUM);
        };

        return Tables;
    }
);